// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v6.33.1
// source: internal/network/logstream/logstream.proto

package proto

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	LogStreamer_StreamLogs_FullMethodName = "/logstream.LogStreamer/StreamLogs"
)

// LogStreamerClient is the client API for LogStreamer service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type LogStreamerClient interface {
	StreamLogs(ctx context.Context, opts ...grpc.CallOption) (grpc.ClientStreamingClient[LogEvent, Empty], error)
}

type logStreamerClient struct {
	cc grpc.ClientConnInterface
}

func NewLogStreamerClient(cc grpc.ClientConnInterface) LogStreamerClient {
	return &logStreamerClient{cc}
}

func (c *logStreamerClient) StreamLogs(ctx context.Context, opts ...grpc.CallOption) (grpc.ClientStreamingClient[LogEvent, Empty], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &LogStreamer_ServiceDesc.Streams[0], LogStreamer_StreamLogs_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[LogEvent, Empty]{ClientStream: stream}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type LogStreamer_StreamLogsClient = grpc.ClientStreamingClient[LogEvent, Empty]

// LogStreamerServer is the server API for LogStreamer service.
// All implementations must embed UnimplementedLogStreamerServer
// for forward compatibility.
type LogStreamerServer interface {
	StreamLogs(grpc.ClientStreamingServer[LogEvent, Empty]) error
	mustEmbedUnimplementedLogStreamerServer()
}

// UnimplementedLogStreamerServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedLogStreamerServer struct{}

func (UnimplementedLogStreamerServer) StreamLogs(grpc.ClientStreamingServer[LogEvent, Empty]) error {
	return status.Errorf(codes.Unimplemented, "method StreamLogs not implemented")
}
func (UnimplementedLogStreamerServer) mustEmbedUnimplementedLogStreamerServer() {}
func (UnimplementedLogStreamerServer) testEmbeddedByValue()                     {}

// UnsafeLogStreamerServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to LogStreamerServer will
// result in compilation errors.
type UnsafeLogStreamerServer interface {
	mustEmbedUnimplementedLogStreamerServer()
}

func RegisterLogStreamerServer(s grpc.ServiceRegistrar, srv LogStreamerServer) {
	// If the following call pancis, it indicates UnimplementedLogStreamerServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&LogStreamer_ServiceDesc, srv)
}

func _LogStreamer_StreamLogs_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(LogStreamerServer).StreamLogs(&grpc.GenericServerStream[LogEvent, Empty]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type LogStreamer_StreamLogsServer = grpc.ClientStreamingServer[LogEvent, Empty]

// LogStreamer_ServiceDesc is the grpc.ServiceDesc for LogStreamer service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var LogStreamer_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "logstream.LogStreamer",
	HandlerType: (*LogStreamerServer)(nil),
	Methods:     []grpc.MethodDesc{},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "StreamLogs",
			Handler:       _LogStreamer_StreamLogs_Handler,
			ClientStreams: true,
		},
	},
	Metadata: "internal/network/logstream/logstream.proto",
}
