// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        v6.33.1
// source: internal/network/logstream/logstream.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type LogEvent struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Seq           uint64                 `protobuf:"varint,1,opt,name=seq,proto3" json:"seq,omitempty"`
	Timestamp     string                 `protobuf:"bytes,2,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	Source        string                 `protobuf:"bytes,3,opt,name=source,proto3" json:"source,omitempty"`
	Payload       []byte                 `protobuf:"bytes,4,opt,name=payload,proto3" json:"payload,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LogEvent) Reset() {
	*x = LogEvent{}
	mi := &file_internal_network_logstream_logstream_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LogEvent) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LogEvent) ProtoMessage() {}

func (x *LogEvent) ProtoReflect() protoreflect.Message {
	mi := &file_internal_network_logstream_logstream_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LogEvent.ProtoReflect.Descriptor instead.
func (*LogEvent) Descriptor() ([]byte, []int) {
	return file_internal_network_logstream_logstream_proto_rawDescGZIP(), []int{0}
}

func (x *LogEvent) GetSeq() uint64 {
	if x != nil {
		return x.Seq
	}
	return 0
}

func (x *LogEvent) GetTimestamp() string {
	if x != nil {
		return x.Timestamp
	}
	return ""
}

func (x *LogEvent) GetSource() string {
	if x != nil {
		return x.Source
	}
	return ""
}

func (x *LogEvent) GetPayload() []byte {
	if x != nil {
		return x.Payload
	}
	return nil
}

type Ack struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Seq           uint64                 `protobuf:"varint,1,opt,name=seq,proto3" json:"seq,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Ack) Reset() {
	*x = Ack{}
	mi := &file_internal_network_logstream_logstream_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Ack) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Ack) ProtoMessage() {}

func (x *Ack) ProtoReflect() protoreflect.Message {
	mi := &file_internal_network_logstream_logstream_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Ack.ProtoReflect.Descriptor instead.
func (*Ack) Descriptor() ([]byte, []int) {
	return file_internal_network_logstream_logstream_proto_rawDescGZIP(), []int{1}
}

func (x *Ack) GetSeq() uint64 {
	if x != nil {
		return x.Seq
	}
	return 0
}

type Empty struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Empty) Reset() {
	*x = Empty{}
	mi := &file_internal_network_logstream_logstream_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Empty) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Empty) ProtoMessage() {}

func (x *Empty) ProtoReflect() protoreflect.Message {
	mi := &file_internal_network_logstream_logstream_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Empty.ProtoReflect.Descriptor instead.
func (*Empty) Descriptor() ([]byte, []int) {
	return file_internal_network_logstream_logstream_proto_rawDescGZIP(), []int{2}
}

var File_internal_network_logstream_logstream_proto protoreflect.FileDescriptor

const file_internal_network_logstream_logstream_proto_rawDesc = "" +
	"\n" +
	"*internal/network/logstream/logstream.proto\x12\tlogstream\"l\n" +
	"\bLogEvent\x12\x10\n" +
	"\x03seq\x18\x01 \x01(\x04R\x03seq\x12\x1c\n" +
	"\ttimestamp\x18\x02 \x01(\tR\ttimestamp\x12\x16\n" +
	"\x06source\x18\x03 \x01(\tR\x06source\x12\x18\n" +
	"\apayload\x18\x04 \x01(\fR\apayload\"\x17\n" +
	"\x03Ack\x12\x10\n" +
	"\x03seq\x18\x01 \x01(\x04R\x03seq\"\a\n" +
	"\x05Empty2D\n" +
	"\vLogStreamer\x125\n" +
	"\n" +
	"StreamLogs\x12\x13.logstream.LogEvent\x1a\x10.logstream.Empty(\x01B\x0fZ\r./proto;protob\x06proto3"

var (
	file_internal_network_logstream_logstream_proto_rawDescOnce sync.Once
	file_internal_network_logstream_logstream_proto_rawDescData []byte
)

func file_internal_network_logstream_logstream_proto_rawDescGZIP() []byte {
	file_internal_network_logstream_logstream_proto_rawDescOnce.Do(func() {
		file_internal_network_logstream_logstream_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_internal_network_logstream_logstream_proto_rawDesc), len(file_internal_network_logstream_logstream_proto_rawDesc)))
	})
	return file_internal_network_logstream_logstream_proto_rawDescData
}

var file_internal_network_logstream_logstream_proto_msgTypes = make([]protoimpl.MessageInfo, 3)
var file_internal_network_logstream_logstream_proto_goTypes = []any{
	(*LogEvent)(nil), // 0: logstream.LogEvent
	(*Ack)(nil),      // 1: logstream.Ack
	(*Empty)(nil),    // 2: logstream.Empty
}
var file_internal_network_logstream_logstream_proto_depIdxs = []int32{
	0, // 0: logstream.LogStreamer.StreamLogs:input_type -> logstream.LogEvent
	2, // 1: logstream.LogStreamer.StreamLogs:output_type -> logstream.Empty
	1, // [1:2] is the sub-list for method output_type
	0, // [0:1] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_internal_network_logstream_logstream_proto_init() }
func file_internal_network_logstream_logstream_proto_init() {
	if File_internal_network_logstream_logstream_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_internal_network_logstream_logstream_proto_rawDesc), len(file_internal_network_logstream_logstream_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   3,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_internal_network_logstream_logstream_proto_goTypes,
		DependencyIndexes: file_internal_network_logstream_logstream_proto_depIdxs,
		MessageInfos:      file_internal_network_logstream_logstream_proto_msgTypes,
	}.Build()
	File_internal_network_logstream_logstream_proto = out.File
	file_internal_network_logstream_logstream_proto_goTypes = nil
	file_internal_network_logstream_logstream_proto_depIdxs = nil
}
